[package]
name = "gst-plugin-nanodet"
version = { workspace = true }
description = "NanoDet tensor decoder for GStreamer analytics pipelines."
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }

[dependencies]
byte-slice-cast = "1"
gst = { workspace = true, features = ["v1_28"] }
gst-analytics = { workspace = true, features = ["v1_28"] }
gst-base = { workspace = true, features = ["v1_28"] }
gst-video = { workspace = true, features = ["v1_28"] }
half = "2.6.0"

[features]
static = []
capi = []
doc = ["gst/v1_28"]

[lib]
name = "gstnanodet"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[lints]
workspace = true

[build-dependencies]
gst-plugin-version-helper = { workspace = true }
