[package]
name = "gst-plugin-ocrs"
version = { workspace = true }
description = "Asynchronous local OCRs analysis for RGB video frames."
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-video-1.0, gobject-2.0, glib-2.0, gmodule-2.0"

[dependencies]
gst = { workspace = true }
gst-base = { workspace = true }
gst-video = { workspace = true }
ocrs = { workspace = true }
rten = { workspace = true }
rten-imageproc = { workspace = true }

[features]
static = []
capi = []
doc = ["gst/v1_24"]

[lib]
name = "gstocrs"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dev-dependencies]
gst-check = { workspace = true }
tempfile = "3.27.0"

[lints]
workspace = true

[build-dependencies]
gst-plugin-version-helper = { workspace = true }
